### ISSUE TITLE
Return all asserted triples from CAMs where queries are matched

### ISSUE THREAD

**Issue by balhoff** [TranslatorIIPrototypes/cam-api#3]

**Comment by patrickkwang** [comment]
Partially addressed by c0008b9bac35b626641539e0a970f0c5c3450ac3

**Comment by patrickkwang** [comment]
a3e7fc45e92dbe55cca7c1b3097704c7b9f41777, 93c2f8cbb78d97e9d301aac6bc8075342ca9055b
