### ISSUE TITLE
Traverse all subtypes of biolink types in SPARQL

### ISSUE THREAD

**Issue by balhoff** [TranslatorIIPrototypes/cam-api#4]
If a biolink type is requested, get OWL class mappings from it, and also any of its subtypes:

`bl:BiologicalProcess ^blml:is_a*/blml:class_uri ?biological_process .`

**Comment by patrickkwang** [comment]
Should we do the same thing with the biolink slots?
`bl:has_participant ^blml:is_a*/blml:slot_uri ?has_participant .`

**Comment by balhoff** [comment]
> Should we do the same thing with the biolink slots?

Yes
